#!/usr/bin/env -S uv run --script
# ///
# requires-python = ">=3.12"
# ///

import subprocess
import sys


def main() -> None:
    try:
        prev = subprocess.check_output(
            "git rev-parse --abbrev-ref @{-1}",
            shell=True,
            text=True,
        ).strip()
    except subprocess.CalledProcessError:
        print("No prior branch in reflog.")
        sys.exit(1)

    print(f"Prev branch → {prev}")
    if input("Delete? [y/N] ").lower() == "y":
        subprocess.check_call(["git", "branch", "-D", prev])
    else:
        print("Aborted.")


if __name__ == "__main__":
    main()
